version: '3.2'

services:
  backend:
    image: docker.pkg.github.com/heycat-svg/jupiter-backend/backend:v0.1.6
    ports:
      - "8080:8080"
    environment:
      - JVM_OPTS="-Xms128m -Xmx128m -XX:PermSize=128m -XX:MaxPermSize=128m"
    networks:
      - demo

  prometheus:
    image: prom/prometheus
    volumes:
      - type: bind
        source: ./prometheus.yml
        target: /etc/prometheus/prometheus.yml
        read_only: true
    ports:
      - "9090:9090"
    networks:
      - demo

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment: 
      GF_RENDERING_SERVER_URL: renderer:8686/render
      GF_RENDERING_CALLBACK_URL: grafana:3000
      GF_LOG_FILTERS: rendering:debug
    networks:
      - demo

  renderer:
    image: grafana/grafana-image-renderer:latest
    ports:
      - "8686:8686"
    networks:
      - demo

networks:
  demo:
    driver: bridge
